[REPLICATED-1887] Add support for random node assignment
replicatedhq/libyaml pull request #89
Opened 2017-02-03 00:17 UTC by divolgin

2017-02-03 00:28 UTC, emosbaugh requested changes
can you add a validate_strategy validation

2017-02-03 00:33 UTC, divolgin commented
@emosbaugh I intentionally left it out because it's a form of documentation in a public repo

2017-02-06 18:12 UTC, emosbaugh commented on validate.go
> +		return fmt.Errorf("Invalid strategy value at key %q", formatted)
can you add `must be one of...`

2017-02-06 18:12 UTC, emosbaugh approved these changes

2017-02-06 19:14 UTC, merged